---
- hosts: all
become: yes
  tasks:
    - name: update
      apt:
        update_cache: yes
        upgrade: "yes"

- hosts: all
  become: yes
  tasks:
    - name: install dependencies
      apt:
        name:
          - git
          - nginx
          - docker.io
          - docker-compose